import { test, expect, type Page } from "@playwright/test"

test.setTimeout(90_000)
const browserErrors = new WeakMap<Page, string[]>()
test.beforeEach(async ({ page }) => {
  const errors: string[] = []
  browserErrors.set(page, errors)
  page.on("pageerror", error => errors.push(error.message))
  page.on("console", message => { if (message.type() === "error") errors.push(message.text()) })
})
test.afterEach(async ({ page }) => {
  expect(browserErrors.get(page), "No runtime or hydration errors").toEqual([])
})

test("ABS filters open on demand, filter ranges, validate and reset", async ({ page, context }) => {
  await context.addCookies([{ name: "lang", value: "ru", domain: "localhost", path: "/" }])
  await page.addInitScript(() => localStorage.setItem("lang", "ru"))
  await page.goto("/products/abs/abs-injection", { waitUntil: "domcontentloaded" })
  const toggle = page.getByRole("button", { name: /^Фильтры/ })
  await expect(toggle).toHaveAttribute("aria-expanded", "false")
  await expect(page.locator('[data-filter-metric="mfr"]')).toHaveCount(0)
  await toggle.click()
  const metric = page.locator('[data-filter-metric="mfr"]')
  const min = metric.getByRole("spinbutton").nth(0)
  const max = metric.getByRole("spinbutton").nth(1)
  const count = page.locator('[aria-live="polite"]').filter({ hasText: "Найдено:" })
  const initial = await count.innerText()
  await min.fill("9999")
  await expect(count).toContainText("Найдено: 0")
  await max.fill("1")
  await expect(metric.getByRole("alert")).toBeVisible()
  await page.getByRole("button", { name: "Сбросить", exact: true }).click()
  await expect(count).toHaveText(initial)
  await expect(min).toHaveValue("")
  await expect(metric.getByRole("alert")).toHaveCount(0)
  await min.fill("19")
  await max.fill("19")
  await expect(count).not.toHaveText(initial)
  await expect(count).not.toContainText("Найдено: 0")
  await toggle.click()
  await expect(toggle).toHaveAttribute("aria-expanded", "false")
})

test("English filters show translated labels on mobile", async ({ page, context }) => {
  await context.addCookies([{ name: "lang", value: "en", domain: "localhost", path: "/" }])
  await page.addInitScript(() => localStorage.setItem("lang", "en"))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/products/abs/abs-injection", { waitUntil: "domcontentloaded" })
  await page.getByRole("button", { name: /^Filters/ }).click()
  const metric = page.locator('[data-filter-metric="mfr"]')
  await expect(metric.locator("legend")).toHaveText("Melt flow rate, g/10 min")
  await expect(metric.getByRole("spinbutton", { name: /from/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await metric.scrollIntoViewIfNeeded()
  await page.screenshot({ path: "tmp/seo-audit/filters-mobile.png" })
})

test("polystyrene filters use decimal fraction sizes and reset", async ({ page, context }) => {
  await context.addCookies([{ name: "lang", value: "ru", domain: "localhost", path: "/" }])
  await page.addInitScript(() => localStorage.setItem("lang", "ru"))
  await page.goto("/products/polystyrene/psv-s", { waitUntil: "domcontentloaded" })
  await page.getByRole("button", { name: /^Фильтры/ }).click()
  const metric = page.locator('[data-filter-metric="fraction"]')
  const count = page.locator('[aria-live="polite"]').filter({ hasText: "Найдено:" })
  const initial = await count.innerText()
  await metric.getByRole("spinbutton").nth(0).fill("0.5")
  await metric.getByRole("spinbutton").nth(1).fill("0.6")
  await expect(count).not.toHaveText(initial)
  await expect(count).not.toContainText("Найдено: 0")
  await page.getByRole("button", { name: "Сбросить", exact: true }).click()
  await expect(count).toHaveText(initial)
})
