-- B2B customer portal: run in Supabase SQL editor before enabling reservations.
create table if not exists public.customer_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  account_type text not null default 'company' check (account_type in ('company', 'individual')),
  company_name text,
  inn text,
  contact_name text,
  phone text,
  email text not null,
  delivery_address text,
  manager_id bigint references public.managers(id) on delete set null,
  access_tier text not null default 'silver' check (access_tier in ('silver', 'gold', 'partner')),
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customer_profiles
  add column if not exists access_tier text not null default 'silver'
  check (access_tier in ('silver', 'gold', 'partner'));

alter table public.orders add column if not exists customer_user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists requested_delivery_date date;
alter table public.orders add column if not exists delivery_address text;
create index if not exists orders_customer_user_id_idx on public.orders(customer_user_id);
create index if not exists orders_customer_email_lower_idx on public.orders(lower(customer_email));

create table if not exists public.customer_reservations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_name text not null,
  quantity numeric(14,3) not null check (quantity > 0),
  unit text not null default 'т' check (unit in ('т', 'уп.')),
  requested_delivery_date date not null,
  comment text,
  status text not null default 'requested' check (status in ('requested', 'confirmed', 'declined', 'completed', 'cancelled')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customer_profiles enable row level security;
alter table public.customer_reservations enable row level security;
create policy "customers read own profile" on public.customer_profiles for select using (auth.uid() = id);
create policy "customers update own profile" on public.customer_profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "customers read own reservations" on public.customer_reservations for select using (auth.uid() = user_id);
create policy "customers create own reservations" on public.customer_reservations for insert with check (auth.uid() = user_id);
create policy "customers update own reservations" on public.customer_reservations for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.create_customer_profile() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.customer_profiles (id, account_type, company_name, inn, contact_name, phone, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'account_type','company'), new.raw_user_meta_data->>'company_name', new.raw_user_meta_data->>'inn', new.raw_user_meta_data->>'contact_name', new.raw_user_meta_data->>'phone', new.email)
  on conflict (id) do nothing;
  return new;
end; $$;
drop trigger if exists on_customer_created on auth.users;
create trigger on_customer_created after insert on auth.users for each row execute procedure public.create_customer_profile();
